version: '3.1'

services:

  rest_db:
    image: mysql
    container_name: rest_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_insta
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - rest_mysql_data:/var/lib/mysql

  storage_db:
    image: mysql
    container_name: storage_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: storage
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
      - storage_mysql_date:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  rest_mysql_data:
  storage_mysql_date: