spring:
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/storage
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

upload:
  path-dir: ./uploads
